CREATE TABLE SUPPORT(
	ID_SUPPORT INT NOT NULL AUTO_INCREMENT,
	ID_COURS INT,
	INTITULE VARCHAR(100),
	DATE_IMPORT DATE,
	
	CONSTRAINT PK_SUPPORT PRIMARY KEY(ID_SUPPORT),
	CONSTRAINT FK_COURS_SUPPORT FOREIGN KEY (ID_COURS) REFERENCES COURS(ID_COURS)
	
);