CREATE TABLE COURS(
	ID_COURS INT NOT NULL AUTO_INCREMENT,
	ID_SEANCE INT,
	INTITULE VARCHAR(50),
	
	CONSTRAINT PK_COURSE PRIMARY KEY(ID_COURS),
	CONSTRAINT FK_COURS_SEANCE FOREIGN KEY (ID_SEANCE) REFERENCES SEANCE(ID_SEANCE)
	
);
	