CREATE TABLE FORMATEUR_EXTERNE (
    ID_FORMATEUR_EXTERNE INT NOT NULL AUTO_INCREMENT,
	NOM VARCHAR(255),
	PRENOM VARCHAR(255),

	CONSTRAINT PK_FORMATEUR_EXTERNE PRIMARY KEY(ID_FORMATEUR_EXTERNE)
);

INSERT INTO FORMATEUR_EXTERNE (NOM, PRENOM) VALUES ('DUPONT', 'JEAN');
INSERT INTO FORMATEUR_EXTERNE (NOM, PRENOM) VALUES ('DUPONT2', 'JEAN2');
