CREATE TABLE FICHE_PRESENCE (
	ID_SEANCE INT NOT NULL,	
	ID_RESSOURCE INT NOT NULL,
	
	
	
	CONSTRAINT PK_PRESENCE PRIMARY KEY(ID_SEANCE,ID_RESSOURCE),
	CONSTRAINT FK_FICHE_SEANCE FOREIGN KEY (ID_SEANCE) REFERENCES SEANCE(ID_SEANCE)
	
);